---
name: Submodule Updates
 
#############################
# Start the job on all push #
#############################
on:
  push:
    branches: master
  pull_request:
    branches: master
 
###############
# Set the Job #
###############
jobs:
  build:
    name: Submodule update
    runs-on: ubuntu-latest
    
    env:
      url: 'git@github.com'
      PARENT_REPOSITORY: 'thomas-pegot/camera_web_server'
      CHECKOUT_BRANCH: 'master'
      PR_AGAINST_BRANCH: 'master'
      OWNER: 'thomas-pegot'
 
    steps:
    
      - name: fix
        shell: bash
        run: |
          git config --global --add url."git@github.com:".insteadOf "https://github.com/"
          
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
 
      ####################################
      # Run the action against code base #
      ####################################
      - name: run action
        id: run_action
        uses: thomas-pegot/github-action-create-pr-parent-submodule@v1
        with:
          github_token: ${{ secrets.RELEASE_HUB_SECRET }}
          parent_repository: ${{ env.PARENT_REPOSITORY }}
          checkout_branch: ${{ env.CHECKOUT_BRANCH}}
          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
          owner: ${{ env.OWNER }}
